spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: qwq140@gmail.com
    password: jb#641954
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true